# Generated by Django 4.1.4 on 2023-03-11 21:54

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.managers.UserManager()),
            ],
        ),
    ]
